services:
  frontend-web:
    container_name: frontend-container-dev
    build:
      context: ./dvlp-front/dvlp-web/
      dockerfile: dev.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./dvlp-front/dvlp-web/src:/app/src
      - ./dvlp-front/dvlp-web/public:/app/public
      - ./dvlp-front/dvlp-web/.env:/app/.env
    networks:
      - sg-services-network

  cloudflared:
    container_name: sg-cloudflared
    image: cloudflare/cloudflared:2026.9.3
    command: tunnel --url http://kong:8000 --no-autoupdate
    networks:
      - sg-services-network
    restart: unless-stopped

  cloudflared-forgot:
    container_name: sg-cloudflared-forgot
    image: cloudflare/cloudflared:2026.9.3
    command: tunnel --url http://ms-forgot-information:8080 --no-autoupdate
    networks:
      - sg-services-network
    restart: unless-stopped

networks:
  sg-services-network:
    external: true
