services:
  backend:
    container_name: backend-container-dev
    build:
      context: ./dvlp-back/src/backend
      dockerfile: dev.Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedOrigins=http://localhost:4200
    command: dotnet watch run
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # Contenedor de desarrollo para el frontend
  frontend-web:
    container_name: frontend-container-dev
    build:
      context: ./dvlp-front/dvlp-web/
      dockerfile: dev.Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
  
  liquibase:
    image: liquibase/liquibase:5.0.1
    container_name: liquibase-container
    volumes:
      - ./dvlp-back/liquibase:/workspace/
      - ./dvlp-back/liquibase/drivers/postgresql-42.7.10.jar:/liquibase/lib/postgresql.jar
    networks:
      - default
    environment:
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      --searchPath=/workspace
      --url=jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
      --username=${DB_USER}
      --password=${DB_PASS}
      --changeLogFile=master.xml
      update

  jenkins:
    container_name: jenkins_container
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: unless-stopped
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
      - sonar-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  nginx:
    image: nginx:latest
    container_name: jenkins-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - jenkins
    networks:
      - jenkins_net
      - sonar-net
    
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_data:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    networks:
      - sonar-net

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  jenkins_net:
  sonar-net: