// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Persistence.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609224036_AbstractClass")]
    partial class AbstractClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Shared.Abstracts.BaseEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("BaseEntity", "app");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("alertTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("alertTypeId");

                    b.HasIndex("busId");

                    b.ToTable("Alert", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.AlertType", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("urgencyLevel")
                        .HasColumnType("integer");

                    b.ToTable("AlertType", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.SavedAlert", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("alertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasIndex("alertId");

                    b.HasIndex("profileId");

                    b.ToTable("SavedAlert", "app");
                });

            modelBuilder.Entity("backend.Modules.BoardingManagement.Domain.Entities.Boarding", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<bool>("action")
                        .HasColumnType("boolean");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("stopId")
                        .HasColumnType("uuid");

                    b.HasIndex("busId");

                    b.HasIndex("profileId");

                    b.HasIndex("stopId");

                    b.ToTable("Boarding", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Brand", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("Brand", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("driverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("gpsStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("lineModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("soatValidity")
                        .HasColumnType("bytea");

                    b.HasIndex("driverId");

                    b.HasIndex("lineModelId");

                    b.HasIndex("schoolId");

                    b.ToTable("Bus", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.ExceptionalDriverUsage", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("busId");

                    b.HasIndex("profileId");

                    b.ToTable("ExceptionalDriverUsage", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("brandId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasIndex("brandId");

                    b.ToTable("Line", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("lineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("modelId")
                        .HasColumnType("uuid");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasIndex("lineId");

                    b.HasIndex("modelId");

                    b.ToTable("LineModel", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Year", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.ToTable("Model", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.ExceptionalRouteUsage", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.HasIndex("profileId");

                    b.HasIndex("routeId");

                    b.ToTable("ExceptionalRouteUsage", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteBusAssignments", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.HasIndex("busId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteBusAssignments", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<TimeSpan>("endTime")
                        .HasColumnType("interval");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("interval");

                    b.Property<string>("targetSector")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasIndex("schoolId");

                    b.ToTable("Route", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStop", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("stopId")
                        .HasColumnType("uuid");

                    b.HasIndex("routeId");

                    b.HasIndex("stopId");

                    b.ToTable("RouteStop", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStudentAssignments", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.HasIndex("profileId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteStudentAssignments", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("cityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("latitude")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("longitude")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasIndex("cityId");

                    b.HasIndex("schoolId");

                    b.ToTable("Stop", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.City", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("country")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.ToTable("City", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid?>("SchoolCampuseid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("campuseId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("SchoolCampuseid");

                    b.HasIndex("campuseId");

                    b.ToTable("Course", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.CourseGroup", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasIndex("courseId");

                    b.HasIndex("profileId");

                    b.ToTable("CourseGroup", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid?>("SchoolEntityid")
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasIndex("SchoolEntityid");

                    b.HasIndex("schoolId");

                    b.ToTable("SchoolCampuse", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("cityId")
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("logo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasIndex("cityId");

                    b.ToTable("School", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Action", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("Action", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Module", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("Module", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("personId")
                        .HasColumnType("uuid");

                    b.HasIndex("personId");

                    b.ToTable("Profile", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ProfileRole", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.HasIndex("profileId");

                    b.HasIndex("roleId");

                    b.ToTable("ProfileRole", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Role", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("permissions")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.ToTable("Role", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.RoleModule", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.HasIndex("moduleId");

                    b.HasIndex("roleId");

                    b.ToTable("RoleModule", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.View", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("View", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewAction", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("actionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("viewId")
                        .HasColumnType("uuid");

                    b.HasIndex("actionId");

                    b.HasIndex("viewId");

                    b.ToTable("ViewAction", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewModule", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("viewId")
                        .HasColumnType("uuid");

                    b.HasIndex("moduleId");

                    b.HasIndex("viewId");

                    b.ToTable("ViewModule", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.DriverLicense", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<byte[]>("drivingLicense")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("licenseExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("licenseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasIndex("profileId");

                    b.ToTable("DriverLicense", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Family", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("observations")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("Family", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.FamilyMember", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<Guid>("familyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasIndex("familyId");

                    b.HasIndex("profileId");

                    b.ToTable("FamilyMember", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.IdentificationType", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ToTable("IdentificationType", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.HasBaseType("backend.Shared.Abstracts.BaseEntity");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("identificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("lastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("residenceAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("identificationId")
                        .IsUnique();

                    b.ToTable("Person", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.HasOne("backend.Modules.AlertManagement.Domain.Entities.AlertType", "alertType")
                        .WithMany("alerts")
                        .HasForeignKey("alertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("alerts")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.AlertManagement.Domain.Entities.Alert", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alertType");

                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.AlertType", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.AlertManagement.Domain.Entities.AlertType", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.SavedAlert", b =>
                {
                    b.HasOne("backend.Modules.AlertManagement.Domain.Entities.Alert", "alerts")
                        .WithMany("savedAlerts")
                        .HasForeignKey("alertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.AlertManagement.Domain.Entities.SavedAlert", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("savedAlerts")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alerts");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.BoardingManagement.Domain.Entities.Boarding", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("boardings")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.BoardingManagement.Domain.Entities.Boarding", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("boardings")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.Stop", "stop")
                        .WithMany("boardings")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Brand", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.Brand", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "driver")
                        .WithMany("driver")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.Bus", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.LineModel", "lineModel")
                        .WithMany("bus")
                        .HasForeignKey("lineModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("buses")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("lineModel");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.ExceptionalDriverUsage", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("exceptionalDriverUsages")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.ExceptionalDriverUsage", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("exceptions")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Brand", "brand")
                        .WithMany("line")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.Line", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.LineModel", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Line", "line")
                        .WithMany("lineModel")
                        .HasForeignKey("lineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Year", "Year")
                        .WithMany("lineModel")
                        .HasForeignKey("modelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Year");

                    b.Navigation("line");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Year", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.FleetManagement.Domain.Entities.Year", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.ExceptionalRouteUsage", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.ExceptionalRouteUsage", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteBusAssignments", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("busAssignments")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.RouteBusAssignments", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("busAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("routes")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.RouteStop", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("routeStops")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.Stop", "stop")
                        .WithMany("routeStops")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("route");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStudentAssignments", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.RouteStudentAssignments", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("studentAssignments")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("studentAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.City", "city")
                        .WithMany("stops")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.RouteManagement.Domain.Entities.Stop", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("stops")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.City", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.SchoolManagement.Domain.Entities.City", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", null)
                        .WithMany("courses")
                        .HasForeignKey("SchoolCampuseid");

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", "campuse")
                        .WithMany()
                        .HasForeignKey("campuseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.SchoolManagement.Domain.Entities.Course", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("campuse");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.CourseGroup", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.Course", "course")
                        .WithMany("courses")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.SchoolManagement.Domain.Entities.CourseGroup", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("courseGroups")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", null)
                        .WithMany("schoolCampuses")
                        .HasForeignKey("SchoolEntityid");

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany()
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.City", "city")
                        .WithMany("schools")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Action", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.Action", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Module", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.Module", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.Profile", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.Person", "person")
                        .WithMany("profiles")
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ProfileRole", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.ProfileRole", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("profileRoles")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Role", "role")
                        .WithMany("profileRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Role", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.Role", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.RoleModule", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.RoleModule", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Module", "module")
                        .WithMany("roleModules")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Role", "role")
                        .WithMany("roleModules")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.View", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.View", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewAction", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Action", "action")
                        .WithMany("viewActions")
                        .HasForeignKey("actionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.ViewAction", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.View", "view")
                        .WithMany("viewActions")
                        .HasForeignKey("viewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("action");

                    b.Navigation("view");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewModule", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.Security.Domain.Entities.ViewModule", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Module", "module")
                        .WithMany("viewModules")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.View", "view")
                        .WithMany("viewModules")
                        .HasForeignKey("viewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("view");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.DriverLicense", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.DriverLicense", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("driverLicenses")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Family", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.Family", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.Family", "family")
                        .WithMany("members")
                        .HasForeignKey("familyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.FamilyMember", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("members")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("family");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.IdentificationType", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.IdentificationType", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.HasOne("backend.Shared.Abstracts.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.Person", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.IdentificationType", "IdentificationType")
                        .WithOne("person")
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.Person", "identificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentificationType");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.Navigation("savedAlerts");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.AlertType", b =>
                {
                    b.Navigation("alerts");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Brand", b =>
                {
                    b.Navigation("line");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("boardings");

                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalDriverUsages");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Year", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("routeStops");

                    b.Navigation("studentAssignments");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("routeStops");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.City", b =>
                {
                    b.Navigation("schools");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.Navigation("buses");

                    b.Navigation("routes");

                    b.Navigation("schoolCampuses");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Action", b =>
                {
                    b.Navigation("viewActions");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Module", b =>
                {
                    b.Navigation("roleModules");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("courseGroups");

                    b.Navigation("driver");

                    b.Navigation("driverLicenses");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("exceptions");

                    b.Navigation("members");

                    b.Navigation("profileRoles");

                    b.Navigation("savedAlerts");

                    b.Navigation("studentAssignments");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Role", b =>
                {
                    b.Navigation("profileRoles");

                    b.Navigation("roleModules");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.View", b =>
                {
                    b.Navigation("viewActions");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Family", b =>
                {
                    b.Navigation("members");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.IdentificationType", b =>
                {
                    b.Navigation("person")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.Navigation("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
