// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Persistence.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603205559_MigrationsUuidEntities")]
    partial class MigrationsUuidEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("alertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("alertTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("alertId");

                    b.HasIndex("alertTypeId");

                    b.HasIndex("busId");

                    b.ToTable("Alert", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.AlertType", b =>
                {
                    b.Property<Guid>("alertTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("urgencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("alertTypeId");

                    b.ToTable("AlertType", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.SavedAlert", b =>
                {
                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("alertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("savedAlertId")
                        .HasColumnType("uuid");

                    b.HasKey("profileId", "alertId");

                    b.HasIndex("alertId");

                    b.ToTable("SavedAlert", "app");
                });

            modelBuilder.Entity("backend.Modules.BoardingManagement.Domain.Entities.Boarding", b =>
                {
                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("stopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("action")
                        .HasColumnType("boolean");

                    b.Property<Guid>("boardingId")
                        .HasColumnType("uuid");

                    b.HasKey("profileId", "busId", "stopId", "dateTime");

                    b.HasIndex("busId");

                    b.HasIndex("stopId");

                    b.ToTable("Boarding", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("brandId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("brandId");

                    b.ToTable("Brand", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("driverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("gpsStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("lineModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("soatValidity")
                        .HasColumnType("bytea");

                    b.HasKey("busId");

                    b.HasIndex("driverId");

                    b.HasIndex("lineModelId");

                    b.HasIndex("schoolId");

                    b.ToTable("Bus", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.ExceptionalDriverUsage", b =>
                {
                    b.Property<Guid>("exceptionalDriverUsageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("exceptionalDriverUsageId");

                    b.HasIndex("busId");

                    b.HasIndex("profileId");

                    b.ToTable("ExceptionalDriverUsage", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.Property<Guid>("lineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("brandId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("lineId");

                    b.HasIndex("brandId");

                    b.ToTable("Line", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.Property<Guid>("lineModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("lineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("modelId")
                        .HasColumnType("uuid");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("lineModelId");

                    b.HasIndex("lineId");

                    b.HasIndex("modelId");

                    b.ToTable("LineModel", "app");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("modelId")
                        .HasColumnType("uuid");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("modelId");

                    b.ToTable("Model", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.ExceptionalRouteUsage", b =>
                {
                    b.Property<Guid>("exceptionalRouteUsageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.HasKey("exceptionalRouteUsageId");

                    b.HasIndex("profileId");

                    b.HasIndex("routeId");

                    b.ToTable("ExceptionalRouteUsage", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteBusAssignments", b =>
                {
                    b.Property<Guid>("busId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeBusAssignmentsId")
                        .HasColumnType("uuid");

                    b.HasKey("busId", "routeId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteBusAssignments", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.Property<Guid>("routeEntityId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("TargetSector")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasKey("routeEntityId");

                    b.HasIndex("schoolId");

                    b.ToTable("Route", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("stopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeStopId")
                        .HasColumnType("uuid");

                    b.HasKey("routeId", "stopId");

                    b.HasIndex("stopId");

                    b.ToTable("RouteStop", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStudentAssignments", b =>
                {
                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("routeStudentAssignmentsId")
                        .HasColumnType("uuid");

                    b.HasKey("profileId", "routeId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteStudentAssignments", "app");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.Property<Guid>("stopId")
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("cityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<decimal>("longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasKey("stopId");

                    b.HasIndex("cityId");

                    b.HasIndex("schoolId");

                    b.ToTable("Stop", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("cityId")
                        .HasColumnType("uuid");

                    b.Property<string>("country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("cityId");

                    b.ToTable("City", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("campuseId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("schoolCampuseId")
                        .HasColumnType("uuid");

                    b.HasKey("courseId");

                    b.HasIndex("campuseId");

                    b.HasIndex("schoolCampuseId");

                    b.ToTable("Course", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.CourseGroup", b =>
                {
                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("courseGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("profileId", "courseId");

                    b.HasIndex("courseId");

                    b.ToTable("CourseGroup", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.Property<Guid>("schoolCampuseId")
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("schoolEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("schoolId")
                        .HasColumnType("uuid");

                    b.HasKey("schoolCampuseId");

                    b.HasIndex("schoolEntityId");

                    b.HasIndex("schoolId");

                    b.ToTable("SchoolCampuse", "app");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.Property<Guid>("schoolEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("cityId")
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("logo")
                        .HasColumnType("bytea");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("schoolEntityId");

                    b.HasIndex("cityId");

                    b.ToTable("School", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Action", b =>
                {
                    b.Property<Guid>("actionId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("actionId");

                    b.ToTable("Action", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("moduleId");

                    b.ToTable("Module", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("personId")
                        .HasColumnType("uuid");

                    b.HasKey("profileId");

                    b.HasIndex("personId");

                    b.ToTable("Profile", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ProfileRole", b =>
                {
                    b.Property<Guid>("profileRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.HasKey("profileRoleId");

                    b.HasIndex("profileId");

                    b.HasIndex("roleId");

                    b.ToTable("ProfileRole", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("permissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("roleId");

                    b.ToTable("Role", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.RoleModule", b =>
                {
                    b.Property<Guid>("roleModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.HasKey("roleModuleId");

                    b.HasIndex("moduleId");

                    b.HasIndex("roleId");

                    b.ToTable("RoleModule", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.View", b =>
                {
                    b.Property<Guid>("viewId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("viewId");

                    b.ToTable("View", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewAction", b =>
                {
                    b.Property<Guid>("viewActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("actionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("viewId")
                        .HasColumnType("uuid");

                    b.HasKey("viewActionId");

                    b.HasIndex("actionId");

                    b.HasIndex("viewId");

                    b.ToTable("ViewAction", "app");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewModule", b =>
                {
                    b.Property<Guid>("viewModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("viewId")
                        .HasColumnType("uuid");

                    b.HasKey("viewModuleId");

                    b.HasIndex("moduleId");

                    b.HasIndex("viewId");

                    b.ToTable("ViewModule", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.DriverLicense", b =>
                {
                    b.Property<Guid>("driverLicenseId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("drivingLicense")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("licenseExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("licenseNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasKey("driverLicenseId");

                    b.HasIndex("profileId");

                    b.ToTable("DriverLicense", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("familyId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("familyId");

                    b.ToTable("Family", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("familyMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("familyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("profileId")
                        .HasColumnType("uuid");

                    b.HasKey("familyMemberId");

                    b.HasIndex("familyId");

                    b.HasIndex("profileId");

                    b.ToTable("FamilyMember", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.IdentificationType", b =>
                {
                    b.Property<Guid>("identificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("identificationId");

                    b.ToTable("IdentificationType", "app");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("personId")
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("identificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("lastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("residenceAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("personId");

                    b.HasIndex("identificationId")
                        .IsUnique();

                    b.ToTable("Person", "app");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.HasOne("backend.Modules.AlertManagement.Domain.Entities.AlertType", "alertType")
                        .WithMany("alerts")
                        .HasForeignKey("alertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("alerts")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alertType");

                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.SavedAlert", b =>
                {
                    b.HasOne("backend.Modules.AlertManagement.Domain.Entities.Alert", "alerts")
                        .WithMany("savedAlerts")
                        .HasForeignKey("alertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("savedAlerts")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alerts");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.BoardingManagement.Domain.Entities.Boarding", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("boardings")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("boardings")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.Stop", "stop")
                        .WithMany("boardings")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "driver")
                        .WithMany("driver")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.LineModel", "lineModel")
                        .WithMany("bus")
                        .HasForeignKey("lineModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("buses")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("lineModel");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.ExceptionalDriverUsage", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("exceptionalDriverUsages")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("exceptions")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Brand", "brand")
                        .WithMany("line")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Line", "line")
                        .WithMany("lineModel")
                        .HasForeignKey("lineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Model", "model")
                        .WithMany("lineModel")
                        .HasForeignKey("modelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("line");

                    b.Navigation("model");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.ExceptionalRouteUsage", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteBusAssignments", b =>
                {
                    b.HasOne("backend.Modules.FleetManagement.Domain.Entities.Bus", "bus")
                        .WithMany("busAssignments")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("busAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("routes")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("routeStops")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.Stop", "stop")
                        .WithMany("routeStops")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("route");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteStudentAssignments", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("studentAssignments")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", "route")
                        .WithMany("studentAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.City", "city")
                        .WithMany("stops")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany("stops")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", "campuse")
                        .WithMany()
                        .HasForeignKey("campuseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", null)
                        .WithMany("courses")
                        .HasForeignKey("schoolCampuseId");

                    b.Navigation("campuse");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.CourseGroup", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.Course", "course")
                        .WithMany("courses")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("courseGroups")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", null)
                        .WithMany("schoolCampuses")
                        .HasForeignKey("schoolEntityId");

                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", "school")
                        .WithMany()
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.HasOne("backend.Modules.SchoolManagement.Domain.Entities.City", "city")
                        .WithMany("schools")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.Person", "person")
                        .WithMany("profiles")
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ProfileRole", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("profileRoles")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Role", "role")
                        .WithMany("profileRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.RoleModule", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Module", "module")
                        .WithMany("roleModules")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Role", "role")
                        .WithMany("roleModules")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewAction", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Action", "action")
                        .WithMany("viewActions")
                        .HasForeignKey("actionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.View", "view")
                        .WithMany("viewActions")
                        .HasForeignKey("viewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("action");

                    b.Navigation("view");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.ViewModule", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Module", "module")
                        .WithMany("viewModules")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.View", "view")
                        .WithMany("viewModules")
                        .HasForeignKey("viewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("view");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.DriverLicense", b =>
                {
                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("driverLicenses")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.Family", "family")
                        .WithMany("members")
                        .HasForeignKey("familyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Security.Domain.Entities.Profile", "profile")
                        .WithMany("members")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("family");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.HasOne("backend.Modules.UserManagement.Domain.Entities.IdentificationType", "IdentificationType")
                        .WithOne("person")
                        .HasForeignKey("backend.Modules.UserManagement.Domain.Entities.Person", "identificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentificationType");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.Alert", b =>
                {
                    b.Navigation("savedAlerts");
                });

            modelBuilder.Entity("backend.Modules.AlertManagement.Domain.Entities.AlertType", b =>
                {
                    b.Navigation("alerts");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Brand", b =>
                {
                    b.Navigation("line");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Bus", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("boardings");

                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalDriverUsages");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Line", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.LineModel", b =>
                {
                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Modules.FleetManagement.Domain.Entities.Model", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.RouteEntity", b =>
                {
                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("routeStops");

                    b.Navigation("studentAssignments");
                });

            modelBuilder.Entity("backend.Modules.RouteManagement.Domain.Entities.Stop", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("routeStops");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.City", b =>
                {
                    b.Navigation("schools");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.Course", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolCampuse", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Modules.SchoolManagement.Domain.Entities.SchoolEntity", b =>
                {
                    b.Navigation("buses");

                    b.Navigation("routes");

                    b.Navigation("schoolCampuses");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Action", b =>
                {
                    b.Navigation("viewActions");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Module", b =>
                {
                    b.Navigation("roleModules");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Profile", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("courseGroups");

                    b.Navigation("driver");

                    b.Navigation("driverLicenses");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("exceptions");

                    b.Navigation("members");

                    b.Navigation("profileRoles");

                    b.Navigation("savedAlerts");

                    b.Navigation("studentAssignments");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.Role", b =>
                {
                    b.Navigation("profileRoles");

                    b.Navigation("roleModules");
                });

            modelBuilder.Entity("backend.Modules.Security.Domain.Entities.View", b =>
                {
                    b.Navigation("viewActions");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Family", b =>
                {
                    b.Navigation("members");
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.IdentificationType", b =>
                {
                    b.Navigation("person")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Modules.UserManagement.Domain.Entities.Person", b =>
                {
                    b.Navigation("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
