<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4c3f7a05-46a2-4649-b4f5-e4c13683d832</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\IRepositories\**" />
    <Compile Remove="Infrastructure\IRepositories\**" />
    <Content Remove="Infrastructure\IRepositories\**" />
    <EmbeddedResource Remove="Infrastructure\IRepositories\**" />
    <None Remove="Infrastructure\IRepositories\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Services\" />
    <Folder Include="Modules\AlertManagement\Infrastructure\Repositories\" />
    <Folder Include="Modules\BoardingManagement\Infrastructure\Repositories\" />
    <Folder Include="Modules\FleetManagement\Domain\Interfaces\" />
    <Folder Include="Modules\FleetManagement\Infrastructure\Repositories\" />
    <Folder Include="Modules\SchoolManagement\Domain\Interfaces\" />
    <Folder Include="Modules\SchoolManagement\Infrastructure\Repositories\" />
    <Folder Include="Modules\RouteManagement\Infrastructure\Repositories\" />
    <Folder Include="Modules\Security\Infrastructure\Repositories\" />
    <Folder Include="Modules\Security\Api\" />
    <Folder Include="Modules\UserManagement\Domain\Interfaces\" />
    <Folder Include="Modules\Security\Infrastructure\Repositories\" />
    <Folder Include="Modules\Security\Api\" />
    <Folder Include="Modules\UserManagement\Domain\Interfaces\" />
    <Folder Include="Modules\UserManagement\Infrastructure\Persistence\Repoitory\" />
  </ItemGroup>

</Project>