DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'migrations') THEN
        CREATE SCHEMA migrations;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS migrations."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Person" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    CONSTRAINT "PK_Person" PRIMARY KEY ("Id")
);

INSERT INTO migrations."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414032734_Initial', '10.0.5');

COMMIT;

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
        CREATE SCHEMA app;
    END IF;
END $EF$;

ALTER TABLE "Person" SET SCHEMA app;

INSERT INTO migrations."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414035240_Initial1', '10.0.5');

COMMIT;

