changeLogFile: liquibase/master.xml
DB_URL: school-guardian.cbe8qus8kx7n.us-east-2.rds.amazonaws.com
DB_PORT: 5432
DB_NAME: school_guardian
DB_USER: user_juan
DB_PASS: 1juAn2!
driver: org.postgresql.Driver