changeLogFile: changelogs/master.xml
url: jdbc:postgresql://school-guardian.cbe8qus8kx7n.us-east-2.rds.amazonaws.com:5432/school_guardian
username: user_juan
password: 1juAn2!
driver: org.postgresql.Driver