// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Persistence.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519192038_migrationEntityIndetificationType")]
    partial class migrationEntityIndetificationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.Academic.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("SchoolCampusecampuseId")
                        .HasColumnType("integer");

                    b.Property<int>("campuseId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolCampusecampuseId");

                    b.HasIndex("campuseId");

                    b.ToTable("Course", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.CourseGroup", b =>
                {
                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<int>("courseId")
                        .HasColumnType("integer");

                    b.HasKey("profileId", "courseId");

                    b.HasIndex("courseId");

                    b.ToTable("CourseGroup", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.SchoolCampuse", b =>
                {
                    b.Property<int>("campuseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("campuseId"));

                    b.Property<int?>("SchoolEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("schoolId")
                        .HasColumnType("integer");

                    b.HasKey("campuseId");

                    b.HasIndex("SchoolEntityId");

                    b.HasIndex("schoolId");

                    b.ToTable("SchoolCampuse", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("alertTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("busId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("alertTypeId");

                    b.HasIndex("busId");

                    b.ToTable("Alert", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.AlertType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("urgencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlertType", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.SavedAlert", b =>
                {
                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<int>("alertId")
                        .HasColumnType("integer");

                    b.HasKey("profileId", "alertId");

                    b.HasIndex("alertId");

                    b.ToTable("SavedAlert", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.DriverLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("drivingLicense")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("licenseExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("licenseNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("profileId");

                    b.ToTable("DriverLicense", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.ExceptionalDriverUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("busId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("busId");

                    b.HasIndex("profileId");

                    b.ToTable("ExceptionalDriverUsage", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.ExceptionalRouteUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("routeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("profileId");

                    b.HasIndex("routeId");

                    b.ToTable("ExceptionalRouteUsage", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Family", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family.FamilyMember", b =>
                {
                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("FamilyId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("FamilyMember", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.School.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("country")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("City", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.School.SchoolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("cityId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("logo")
                        .HasColumnType("bytea");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.ToTable("School", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Action", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("Action", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Module", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("Module", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("permissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("id");

                    b.ToTable("Role", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.RoleModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("moduleId")
                        .HasColumnType("integer");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("moduleId");

                    b.HasIndex("roleId");

                    b.ToTable("RoleModule", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.View", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("View", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.ViewAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("actionId")
                        .HasColumnType("integer");

                    b.Property<int>("viewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("actionId");

                    b.HasIndex("viewId");

                    b.ToTable("ViewAction", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.ViewModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("ViewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ViewId");

                    b.ToTable("ViewModule", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Boarding", b =>
                {
                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<int>("busId")
                        .HasColumnType("integer");

                    b.Property<int>("stopId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("action")
                        .HasColumnType("boolean");

                    b.HasKey("profileId", "busId", "stopId", "dateTime");

                    b.HasIndex("busId");

                    b.HasIndex("stopId");

                    b.ToTable("Boarding", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Brand", b =>
                {
                    b.Property<int>("brandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("brandId"));

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("brandId");

                    b.ToTable("Brand", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("driverId")
                        .HasColumnType("integer");

                    b.Property<bool>("gpsStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("lineModelId")
                        .HasColumnType("integer");

                    b.Property<int>("schoolId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("soatValidity")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("driverId");

                    b.HasIndex("lineModelId");

                    b.HasIndex("schoolId");

                    b.ToTable("Bus", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Line", b =>
                {
                    b.Property<int>("lineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("lineId"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("lineId");

                    b.HasIndex("brandId");

                    b.ToTable("Line", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.LineModel", b =>
                {
                    b.Property<int>("lineModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("lineModelId"));

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<int>("lineId")
                        .HasColumnType("integer");

                    b.Property<int>("modelId")
                        .HasColumnType("integer");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("lineModelId");

                    b.HasIndex("lineId");

                    b.HasIndex("modelId");

                    b.ToTable("LineModel", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Model", b =>
                {
                    b.Property<int>("modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("modelId"));

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("modelId");

                    b.ToTable("Model", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteBusAssignments", b =>
                {
                    b.Property<int>("busId")
                        .HasColumnType("integer");

                    b.Property<int>("routeId")
                        .HasColumnType("integer");

                    b.HasKey("busId", "routeId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteBusAssignments", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("TargetSector")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("schoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("schoolId");

                    b.ToTable("Route", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteStop", b =>
                {
                    b.Property<int>("routeId")
                        .HasColumnType("integer");

                    b.Property<int>("stopId")
                        .HasColumnType("integer");

                    b.HasKey("routeId", "stopId");

                    b.HasIndex("stopId");

                    b.ToTable("RouteStop", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteStudentAssignments", b =>
                {
                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<int>("routeId")
                        .HasColumnType("integer");

                    b.HasKey("profileId", "routeId");

                    b.HasIndex("routeId");

                    b.ToTable("RouteStudentAssignments", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("cityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<decimal>("longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<int>("schoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.HasIndex("schoolId");

                    b.ToTable("Stop", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.IdentificationType", b =>
                {
                    b.Property<int>("identificationId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("identificationId");

                    b.ToTable("IdentificationType", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.Person", b =>
                {
                    b.Property<int>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("personId"));

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("identificationId")
                        .HasColumnType("integer");

                    b.Property<string>("lastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("residenceAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("personId");

                    b.ToTable("Person", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("personId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("personId");

                    b.ToTable("Profile", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.ProfileRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("profileId")
                        .HasColumnType("integer");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("profileId");

                    b.HasIndex("roleId");

                    b.ToTable("ProfileRole", "app");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.Course", b =>
                {
                    b.HasOne("backend.Domain.Entities.Academic.SchoolCampuse", null)
                        .WithMany("courses")
                        .HasForeignKey("SchoolCampusecampuseId");

                    b.HasOne("backend.Domain.Entities.Academic.SchoolCampuse", "campuse")
                        .WithMany()
                        .HasForeignKey("campuseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("campuse");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.CourseGroup", b =>
                {
                    b.HasOne("backend.Domain.Entities.Academic.Course", "course")
                        .WithMany("courses")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("courseGroups")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.SchoolCampuse", b =>
                {
                    b.HasOne("backend.Domain.Entities.School.SchoolEntity", null)
                        .WithMany("schoolCampuses")
                        .HasForeignKey("SchoolEntityId");

                    b.HasOne("backend.Domain.Entities.School.SchoolEntity", "school")
                        .WithMany()
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.Alert", b =>
                {
                    b.HasOne("backend.Domain.Entities.Alerts.AlertType", "alertType")
                        .WithMany("alerts")
                        .HasForeignKey("alertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.Bus", "bus")
                        .WithMany("alerts")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alertType");

                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.SavedAlert", b =>
                {
                    b.HasOne("backend.Domain.Entities.Alerts.Alert", "alerts")
                        .WithMany("savedAlerts")
                        .HasForeignKey("alertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("savedAlerts")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alerts");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.DriverLicense", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("driverLicenses")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.ExceptionalDriverUsage", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", null)
                        .WithMany("exceptions")
                        .HasForeignKey("ProfileId");

                    b.HasOne("backend.Domain.Entities.Transport.Bus", "bus")
                        .WithMany("exceptionalDriverUsages")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany()
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("backend.Domain.Entities.Exceptions.ExceptionalRouteUsage", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.RouteEntity", "route")
                        .WithMany("exceptionalRouteUsages")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family.FamilyMember", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family.Family", "Family")
                        .WithMany("members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Users.Profile", "Profile")
                        .WithMany("members")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Domain.Entities.School.SchoolEntity", b =>
                {
                    b.HasOne("backend.Domain.Entities.School.City", "city")
                        .WithMany("schools")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.RoleModule", b =>
                {
                    b.HasOne("backend.Domain.Entities.Security.Module", "Module")
                        .WithMany("roleModules")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Security.Role", "Role")
                        .WithMany("roleModules")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.ViewAction", b =>
                {
                    b.HasOne("backend.Domain.Entities.Security.Action", "action")
                        .WithMany("viewActions")
                        .HasForeignKey("actionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Security.View", "view")
                        .WithMany("viewActions")
                        .HasForeignKey("viewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("action");

                    b.Navigation("view");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.ViewModule", b =>
                {
                    b.HasOne("backend.Domain.Entities.Security.Module", "Module")
                        .WithMany("viewModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Security.View", "View")
                        .WithMany("viewModules")
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("View");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Boarding", b =>
                {
                    b.HasOne("backend.Domain.Entities.Transport.Bus", "bus")
                        .WithMany("boardings")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("boardings")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.Stop", "stop")
                        .WithMany("boardings")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("profile");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Bus", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", "driver")
                        .WithMany("driver")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.LineModel", "lineModel")
                        .WithMany("bus")
                        .HasForeignKey("lineModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.School.SchoolEntity", "school")
                        .WithMany("buses")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("lineModel");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Line", b =>
                {
                    b.HasOne("backend.Domain.Entities.Transport.Brand", "brand")
                        .WithMany("line")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.LineModel", b =>
                {
                    b.HasOne("backend.Domain.Entities.Transport.Line", "line")
                        .WithMany("lineModel")
                        .HasForeignKey("lineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.Model", "model")
                        .WithMany("lineModel")
                        .HasForeignKey("modelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("line");

                    b.Navigation("model");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteBusAssignments", b =>
                {
                    b.HasOne("backend.Domain.Entities.Transport.Bus", "bus")
                        .WithMany("busAssignments")
                        .HasForeignKey("busId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.RouteEntity", "route")
                        .WithMany("busAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bus");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteEntity", b =>
                {
                    b.HasOne("backend.Domain.Entities.School.SchoolEntity", "school")
                        .WithMany("routes")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteStop", b =>
                {
                    b.HasOne("backend.Domain.Entities.Transport.RouteEntity", "route")
                        .WithMany("routeStops")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.Stop", "stop")
                        .WithMany("routeStops")
                        .HasForeignKey("stopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("route");

                    b.Navigation("stop");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteStudentAssignments", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("studentAssignments")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Transport.RouteEntity", "route")
                        .WithMany("studentAssignments")
                        .HasForeignKey("routeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("route");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Stop", b =>
                {
                    b.HasOne("backend.Domain.Entities.School.City", "city")
                        .WithMany("stops")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.School.SchoolEntity", "school")
                        .WithMany("stops")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("school");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.IdentificationType", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Person", "person")
                        .WithOne("IdentificationType")
                        .HasForeignKey("backend.Domain.Entities.Users.IdentificationType", "identificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.Profile", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Person", "person")
                        .WithMany("profiles")
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.ProfileRole", b =>
                {
                    b.HasOne("backend.Domain.Entities.Users.Profile", "profile")
                        .WithMany("profileRoles")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Security.Role", "role")
                        .WithMany("profileRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.Course", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Domain.Entities.Academic.SchoolCampuse", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.Alert", b =>
                {
                    b.Navigation("savedAlerts");
                });

            modelBuilder.Entity("backend.Domain.Entities.Alerts.AlertType", b =>
                {
                    b.Navigation("alerts");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family.Family", b =>
                {
                    b.Navigation("members");
                });

            modelBuilder.Entity("backend.Domain.Entities.School.City", b =>
                {
                    b.Navigation("schools");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Domain.Entities.School.SchoolEntity", b =>
                {
                    b.Navigation("buses");

                    b.Navigation("routes");

                    b.Navigation("schoolCampuses");

                    b.Navigation("stops");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Action", b =>
                {
                    b.Navigation("viewActions");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Module", b =>
                {
                    b.Navigation("roleModules");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.Role", b =>
                {
                    b.Navigation("profileRoles");

                    b.Navigation("roleModules");
                });

            modelBuilder.Entity("backend.Domain.Entities.Security.View", b =>
                {
                    b.Navigation("viewActions");

                    b.Navigation("viewModules");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Brand", b =>
                {
                    b.Navigation("line");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Bus", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("boardings");

                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalDriverUsages");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Line", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.LineModel", b =>
                {
                    b.Navigation("bus");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Model", b =>
                {
                    b.Navigation("lineModel");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.RouteEntity", b =>
                {
                    b.Navigation("busAssignments");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("routeStops");

                    b.Navigation("studentAssignments");
                });

            modelBuilder.Entity("backend.Domain.Entities.Transport.Stop", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("routeStops");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.Person", b =>
                {
                    b.Navigation("IdentificationType")
                        .IsRequired();

                    b.Navigation("profiles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Users.Profile", b =>
                {
                    b.Navigation("boardings");

                    b.Navigation("courseGroups");

                    b.Navigation("driver");

                    b.Navigation("driverLicenses");

                    b.Navigation("exceptionalRouteUsages");

                    b.Navigation("exceptions");

                    b.Navigation("members");

                    b.Navigation("profileRoles");

                    b.Navigation("savedAlerts");

                    b.Navigation("studentAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
