import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    height: "100%",
    position: "relative",
    backgroundColor: "#FFFFFF",
  },
  topControls: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    zIndex: 2,
    elevation: 4,
  },
  titlePill: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 4,
  },
  notificationButton: {
    flexShrink: 0,
  },
  title: {
    fontSize: 14,
    fontWeight: "700",
  },
  gpsCard: {
    width: "100%",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    flexShrink: 1,
  },
  gpsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 24,
  },
  gpsLabel: {
    fontSize: 12,
    fontWeight: "bold",
    flexShrink: 0,
  },
  gpsValue: {
    fontSize: 12,
    textAlign: "right",
    flexShrink: 1,
    marginLeft: 12,
  },
  centerButton: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 6,
    marginBottom: 12,
    marginRight: 16,
    alignSelf: "flex-end",
  },
  locationInfoContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 72,
    alignItems: "stretch",
    zIndex: 2,
    elevation: 5,
  },
  loadingContainer: {
    position: "absolute",
    top: 100,
    left: 16,
    right: 16,
    zIndex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: "rgba(15, 23, 42, 0.72)",
  },
  loadingText: {
    color: "#FFFFFF",
    fontSize: 12,
    textAlign: "center",
  },
  bottomBarOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 3,
    elevation: 7,
  },
});
